// Global Styles - Pre-composed style combinations for UI patterns

export const GLOBAL_STYLES = {
  buttons: {
    primary: 'bg-primary text-primary-foreground hover:bg-primary/90 px-6 py-2.5 rounded-lg font-medium transition-colors shadow-md hover:shadow-lg',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/90 px-6 py-2.5 rounded-lg font-medium transition-colors shadow-md hover:shadow-lg',
    outline: 'border-2 border-primary text-primary hover:bg-primary hover:text-primary-foreground px-6 py-2.5 rounded-lg font-medium transition-all',
    ghost: 'text-primary hover:bg-primary/10 px-6 py-2.5 rounded-lg font-medium transition-colors',
    danger: 'bg-destructive text-destructive-foreground hover:bg-destructive/90 px-6 py-2.5 rounded-lg font-medium transition-colors shadow-md',
    loading: 'opacity-50 cursor-not-allowed',
  },
  metricCards: {
    container: 'bg-card text-card-foreground rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow',
    icon: 'w-12 h-12 rounded-full flex items-center justify-center mb-4',
    title: 'text-sm font-medium text-muted-foreground mb-1',
    value: 'text-3xl font-bold mb-2',
    trend: 'flex items-center gap-1 text-sm',
    trendUp: 'text-success',
    trendDown: 'text-error',
  },
  dataTables: {
    container: 'bg-card rounded-lg shadow-md overflow-hidden',
    table: 'w-full',
    header: 'bg-muted/50 border-b border-border',
    headerCell: 'px-6 py-3 text-start text-xs font-medium text-muted-foreground uppercase tracking-wider',
    row: 'hover:bg-muted/50 transition-colors border-b border-border last:border-0',
    rowStriped: 'even:bg-muted/20',
    cell: 'px-6 py-4 text-sm',
    sortable: 'cursor-pointer hover:text-foreground flex items-center gap-2',
    pagination: 'flex items-center justify-between px-6 py-4 border-t border-border',
    skeleton: 'animate-pulse bg-muted rounded h-4',
  },
  charts: {
    container: 'bg-card rounded-lg shadow-md p-6',
    title: 'text-lg font-semibold mb-4',
    responsive: 'w-full h-80',
    loading: 'flex items-center justify-center h-80',
    empty: 'flex flex-col items-center justify-center h-80 text-muted-foreground',
    colors: {
      primary: 'hsl(221, 83%, 53%)',
      secondary: 'hsl(262, 83%, 58%)',
      accent: 'hsl(142, 76%, 36%)',
      warning: 'hsl(45, 93%, 47%)',
      info: 'hsl(199, 89%, 48%)',
    },
  },
  forms: {
    input: 'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    inputError: 'border-destructive focus-visible:ring-destructive',
    inputSuccess: 'border-success focus-visible:ring-success',
    label: 'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
    error: 'text-sm font-medium text-destructive mt-1',
    success: 'text-sm font-medium text-success mt-1',
  },
  layouts: {
    dashboard: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6',
    page: 'min-h-screen bg-background p-6',
    header: 'sticky top-0 z-50 w-full border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60',
    sidebar: 'fixed inset-y-0 start-0 w-64 border-e border-border bg-card transition-transform',
    sidebarCollapsed: 'w-16',
    main: 'flex-1 ms-0 md:ms-64 transition-all',
  },
  navigation: {
    link: 'flex items-center gap-3 px-4 py-2.5 rounded-lg text-sm font-medium transition-colors hover:bg-muted',
    linkActive: 'bg-primary/10 text-primary',
    linkInactive: 'text-muted-foreground hover:text-foreground',
    mobile: 'fixed bottom-0 inset-x-0 z-50 border-t border-border bg-card md:hidden',
  },
  rtl: {
    container: '[dir="rtl"]',
    text: '[dir="rtl"] text-right',
    flexReverse: '[dir="rtl"] flex-row-reverse',
  },
} as const;
